### ISSUE TITLE
Lobby chat issue

### ISSUE THREAD

**Issue by csatacsirke** [shadowwolf0189/LeagueChat#1]
When logged in from both the app and the game, you can't see the team chat (in the game ).

**Comment by Jesusrz001** [comment]
Hmm so it restricts Client chat essentially?

**Comment by shadowwolf0189** [comment]
@Jesusrz001 But only in-game. I do know for a fact it works for both in the client. Will look into this and post an update.

**Comment by shadowwolf0189** [comment]
@csatacsirke I wasn't able to replicate this. Can you explain a bit further? I was able to see chat between me, my friends, and my fellow summoners while being logged in both places.

**Comment by csatacsirke** [comment]
I can't see chat during champ select, and just before that. Others can see what I type. Also EUNE server. Could it be only my machine? =/

**Comment by shadowwolf0189** [comment]
@csatacsirke I might have to say yes. Until I get any further reports of this I'm going to close this issue. I've seen the League client be unable to print chat before, multiple times. We all know how well Riot's client actually works :-1: 

DO let me know if you can't get this fixed.
